name: screen_pal
description:
  Screen Pal is a movies and TV shows app that provides information about movies
  and TV shows.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.1.1+1

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  # sdk
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # dart
  dio: ^5.3.2
  envied: ^0.5.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  logger: ^2.0.2

  # flutter
  flutter_markdown: ^0.6.18+2
  flutter_riverpod: ^2.3.6
  go_router: ^12.1.1
  package_info_plus: ^4.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.14

  # styles
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.2.0
  # google_fonts: ^6.1.0

  # widgets
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0

  # native
  flutter_native_splash: ^2.3.3

  # annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  # from sdk
  flutter_test:
    sdk: flutter

  # test utils
  mockito: ^5.4.2
  network_image_mock: ^2.1.1

  # native
  icons_launcher: ^2.1.3

  # lints
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.1.1

  # code generators
  build_runner: ^2.4.6
  envied_generator: ^0.5.3
  freezed: ^2.4.1
  go_router_builder: ^2.4.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tmdb/
    - policies/

    # fonts license
    - assets/fonts/Rubik/OFL.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/static/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/static/Rubik-Black.ttf
          weight: 900

        #
        - asset: assets/fonts/Rubik/static/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
