name: screen_pal
description:
  A comprehensive movie and TV show app that provides in-depth information about
  movies and TV shows from around the world.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.2.0
  google_fonts: ^5.1.0
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  envied: ^0.3.0+3
  equatable: ^2.0.5
  get_it: ^7.6.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  go_router: ^10.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.3
  mockito: ^5.4.2
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  riverpod_generator: ^2.2.4
  custom_lint: ^0.4.0
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/tmdb/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
