name: CD - Web Release

# https://igorsteblii.medium.com/deploy-flutter-web-app-with-github-actions-or-gitlab-ci-cd-on-pages-in-5-min-6a473ac79101
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.x"

      - name: Get dependencies
        run: flutter pub get

      # https://stackoverflow.com/a/63350136/19337625
      - name: Generate prod environment
        run: |
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          dart run build_runner build --delete-conflicting-outputs

      - name: Add github-pages 404 handler
        working-directory: web
        run: echo "${{secrets.GH_PAGES_404}}" > 404.html

      - name: Flutter build web release
        run:
          flutter build web --web-renderer canvaskit --release --base-href
          "/screen_pal/"

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-web
          path: ./build/web

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build-web
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
