name: CD Web

# https://igorsteblii.medium.com/deploy-flutter-web-app-with-github-actions-or-gitlab-ci-cd-on-pages-in-5-min-6a473ac79101
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: '3.x'

      - name: Get dependencies
        run: flutter pub get

      # https://stackoverflow.com/a/63350136/19337625
      - name: Create env file
        run: echo "${{ secrets.DOT_ENV_FILE }}" > .env

      - name: Run build_runner to generate _Env class
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Flutter build web
        run: flutter build web --release --base-href "${{ secrets.BASE_HREF }}"

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-web
          path: ./build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build-web
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
