name: CI/CD - Test and Preview

on:
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.10.x]

    steps:
      - name: Setup Flutter v${{ matrix.flutter-version }} SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ matrix.flutter-version }}

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Get dependencies
        run: flutter pub get

      - name: Generate dev environment
        run: |
          echo "${{ secrets.DEV_ENV_FILE }}" > .env
          dart run build_runner build -d

      - name: Test with min 80% coverage
        run: |
          flutter test --coverage
          dart pub global activate clean_coverage
          clean_coverage clean coverage/lcov.info --exclusions "**.g.dart","**.freezed.dart","**/interfaces/**"
          dart pub global activate dlcov
          dlcov -c 80

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: ./coverage/lcov.info

      - name: Add netlify 404 handler
        working-directory: web
        run: echo '${{secrets.NETLIFY_404}}' > 404.html

      - name: Flutter build web profile
        run: flutter build web --web-renderer canvaskit --profile

      - name: Upload build-web-preview
        uses: actions/upload-artifact@v2
        with:
          name: build-web-preview
          path: ./build/web

  deploy-preview:
    needs: test
    permissions:
      pull-requests: read
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout preview branch
        uses: actions/checkout@v3
        with:
          ref: preview

      - name: Download build-web-preview
        uses: actions/download-artifact@v2
        with:
          name: build-web-preview
          path: ./

      - name: Push build to preview branch
        env:
          PR_REF: https://github.com/KeidsID/screen_pal/pull/${{github.event.pull_request.number}}
        run: |
          git config --global user.email "keidscode@gmail.com"
          git config --global user.name "KeidsID"
          git add .
          git commit -m "web-preview build from PR ${{env.PR_REF}}"
          git push origin preview
