name: CI

on:
  pull_request_review:
    types:
      - submitted
      - edited

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.x"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: flutter pub get

      - name: Create env file
        run: echo "${{ secrets.DOT_ENV_FILE }}" > .env

      - name: Run build_runner to generate _Env class
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Test with coverage
        run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
